In [28]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [3]:
df = pd.read_csv('Iris.csv')

In [11]:
df.sample(5)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
34,35,4.9,3.1,1.5,0.1,Iris-setosa
131,132,7.9,3.8,6.4,2.0,Iris-virginica
111,112,6.4,2.7,5.3,1.9,Iris-virginica
75,76,6.6,3.0,4.4,1.4,Iris-versicolor
93,94,5.0,2.3,3.3,1.0,Iris-versicolor

In [5]:
df.shape

(150, 6)

In [6]:
df['Species'].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [44]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [46]:
from ydata_profiling import ProfileReport
prof = ProfileReport(df)
prof.to_file(output_file='output.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|█████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 22631.14it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [12]:
df = df.drop(columns=['Id'])

In [13]:
df

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [23]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,:4], df.iloc[:,4], test_size=0.2, random_state=42)

In [24]:
trf_scale = ColumnTransformer([('scl', StandardScaler(), slice(0, 4))])

In [36]:
trf_model = LogisticRegression(max_iter=200)

In [37]:
pipe = Pipeline([
    ('scale',trf_scale),
    ('model',trf_model)
])

In [38]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('scale',
                 ColumnTransformer(transformers=[('scl', StandardScaler(),
                                                  slice(0, 4, None))])),
                ('model', LogisticRegression(max_iter=200))])

In [39]:
y_pred = pipe.predict(X_test)

In [40]:
accuracy_score(y_test, y_pred)

1.0

In [41]:
import pickle

In [42]:
pickle.dump(pipe, open('pipe.pkl', 'wb'))